name: GitHub Actions Demo 2
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
      pet:
        description: 'My pet'
        required: false
        default: 'Black cat'
jobs:
  say_hello_pet:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello $NAME!
          echo -in $HOME
          echo My pet is $PET
        env:
          NAME: ${{ github.event.inputs.name }}
          HOME: ${{ github.event.inputs.home }}
          PET: ${{ github.event.inputs.pet }}
