name: GitHub Actions Demo 3
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Title of PR"
        required: true
        default: "PR"
      body:
        description: "Body of PR"
        required: true
        default: "PR"
      head:
        description: "Head branch of PR"
        required: true
        default: "sample-branch"
      base:
        description: "Base branch of PR"
        required: true
        default: "main"

jobs:
  say_hello_pet_clothes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" -H "Content-Type: application/json; charset=utf-8" 
          https://api.github.com/repos/okada-shun/ts-api-sample/pulls 
          -d "{\"title\":$TITLE,\"body\":$BODY,\"head\":$HEAD,\"base\":$BASE}"
      env:
          TITLE: ${{ github.event.inputs.title }}
          BODY: ${{ github.event.inputs.body }}
          HEAD: ${{ github.event.inputs.head }}
          BASE: ${{ github.event.inputs.base }}
