name: GitHub Actions Demo 3
on: push
jobs:
  say_hello_pet_clothes:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.ACTION_TOKEN }}" -H "Content-Type: application/json; charset=utf-8" https://api.github.com/repos/okada-shun/ts-api-sample/pulls -d "{\"title\":\"PR by GitHub api\",\"head\":\"sample-branch\",\"body\":\"PR by GitHub api\",\"base\":\"main\"}"
